
# Initialising the order list
burger_price = 20
coffee_price = 30
tea_price = 10

burger_quantity = 0
coffee_quantity = 0
tea_quantity = 0

# For taking orders:
while True:
    print("Welcome to the PoS System")
    print("1. Burger    ₹20")
    print("2. Coffee    ₹30")
    print("3. Tea       ₹10")
    print("0. Exit and Print Bill")

    order = input("Enter your order number: ")

    if order == "0":
        break
    elif order == "1":
        quantity = int(input("How many Burgers? "))
        burger_quantity += quantity
    elif order == "2":
        quantity = int(input("How many Coffees? "))
        coffee_quantity += quantity
    elif order == "3":
        quantity = int(input("How many Teas? "))
        tea_quantity += quantity
    else:
        print("Invalid choice. Please select from the menu.")

# For Calculating the total bill generated by the PoS
total_bill = (burger_price * burger_quantity) + (coffee_price * coffee_quantity) + (tea_price * tea_quantity)

print("Your Order Summary:")
print("--------------------")
if burger_quantity > 0:
    print("Burger: " + str(burger_quantity) + " x ₹" + str(burger_price) + " = ₹" + str(burger_price * burger_quantity))
if coffee_quantity > 0:
    print("Coffee: " + str(coffee_quantity) + " x ₹" + str(coffee_price) + " = ₹" + str(coffee_price * coffee_quantity))
if tea_quantity > 0:
    print("Tea: " + str(tea_quantity) + " x ₹" + str(tea_price) + " = ₹" + str(tea_price * tea_quantity))


print("--------------------")
print("Total Bill: ₹" + str(total_bill))
print("--------------------")
print("Thanks For Coming, Visit Again!")
print("")